export const CHAIN = {
  ["Cosmos Hub"]: "cosmoshub-4",
  ["Osmosis"]: "osmosis-1",
  ["Secret Network"]: "secret-4",
  ["Regen"]: "regen-1",
  ["Akash"]: "akashnet-2",
  ["SifChain"]: "sifchain-1",
  ["Stargaze"]: "stargaze-1",
  ["Sentinel"]: "sentinelhub-2",
  ["Persistence"]: "core-1",
  ["Kava"]: "kava-2222-10",
  ["Crypto.org"]: "crypto-org-chain-mainnet-1",
  ["IRISnet"]: "irishub-1",
  ["Agoric"]: "agoric-3",
  ["Axelar"]: "axelar-dojo-1",
  ["Certik"]: "shentu-2.2",
  ["ixo"]: "impacthub-3",
  ["e-Money"]: "emoney-3",
  ["Juno"]: "juno-1",
  ["Sommelier"]: "sommelier-3",
  ["Umee"]: "umee-1",
  ["Evmos"]: "evmos_9000-2",
  ["Bostrom"]: "bostrom",
  ["Starname"]: "iov-mainnet-ibc",
  ["Gravity Bridge"]: "gravity-bridge-3",
};
